OLED_ENABLE = yes
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
EXTRAKEY_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_MAP_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
VIALRGB_ENABLE = no
QMK_SETTINGS = no
COMBO_ENABLE = no				#COMBOS
KEY_OVERRIDE_ENABLE = no
RGB_MATRIX_ENABLE = no
DEFERRED_EXEC_ENABLE = no
EXTRAFLAGS += -flto


LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes           #MOUSEKEYS
REPEAT_KEY_ENABLE = yes
UNICODE_ENABLE = no
UNICODEMAP_ENABLE = no
UCIS_ENABLE = no
UNICODE_COMMON = no

AUTOCORRECT_ENABLE ?= no
CAPS_WORD_ENABLE ?=yes
GRAVE_ESC_ENABLE ?= no
NKRO_ENABLE ?= no
SPACE_CADET_ENABLE ?= no
TAP_DANCE_ENABLE ?= no

ACHORDION_ENABLE ?= yes
ifeq ($(strip $(ACHORDION_ENABLE)), yes)
	OPT_DEFS += -DACHORDION_ENABLE
	SRC += features/achordion.c
endif

CUSTOM_SHIFT_KEYS_ENABLE ?= no
ifeq ($(strip $(CUSTOM_SHIFT_KEYS_ENABLE)), yes)
	OPT_DEFS += -DCUSTOM_SHIFT_KEYS_ENABLE
	SRC += features/custom_shift_keys.c
endif

LAYER_LOCK_ENABLE ?= no
ifeq ($(strip $(LAYER_LOCK_ENABLE)), yes)
	OPT_DEFS += -DLAYER_LOCK_ENABLE
	SRC += features/layer_lock.c
endif

ORBITAL_MOUSE_ENABLE ?= no
ifeq ($(strip $(ORBITAL_MOUSE_ENABLE)), yes)
	MOUSE_ENABLE = yes
	OPT_DEFS += -DORBITAL_MOUSE_ENABLE
	SRC += features/orbital_mouse.c
endif

SENTENCE_CASE_ENABLE ?= no
ifeq ($(strip $(SENTENCE_CASE_ENABLE)), yes)
	OPT_DEFS += -DSENTENCE_CASE_ENABLE
	SRC += features/sentence_case.c
endif

